### ISSUE TITLE
原代码就会产生三个不同的实例

### ISSUE THREAD

**Issue by aaronfledermaus** [ByteLegendQuest/java-fix-same-reference#139]
Code中运行结果：
com.bytelegend.pet.Cat@1f32e575
com.bytelegend.pet.Cat@279f2327
com.bytelegend.pet.Cat@2ff4acd0

**Comment by blindpirate** [comment]
Closed by https://github.com/ByteLegendQuest/java-fix-same-reference/commit/cce2b6587f6270fdb741078471cb12160f883b00
